open_system('gm_untitled');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/delay_process_section1_tap0', 'user1');
annotate_port('gm_untitled/butterbp/delay_process_section1_tap0', 0, 1, 'cp : 0.46 ns');
annotate_port('gm_untitled/butterbp/delay_process_section1_tap0', 1, 1, 'cp : 8.046 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/t', 'user2');
annotate_port('gm_untitled/butterbp/t', 0, 1, 'cp : 0.46 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/t1', 'user2');
annotate_port('gm_untitled/butterbp/t1', 0, 1, 'cp : 0.46 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/multiplier5', 'user2');
annotate_port('gm_untitled/butterbp/multiplier5', 0, 1, 'cp : 4.386 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/dtc17', 'user2');
annotate_port('gm_untitled/butterbp/dtc17', 0, 1, 'cp : 4.386 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/Sub', 'user2');
annotate_port('gm_untitled/butterbp/Sub', 0, 1, 'cp : 6.1255 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/dtc18', 'user2');
annotate_port('gm_untitled/butterbp/dtc18', 0, 1, 'cp : 6.1255 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/dtc19', 'user2');
annotate_port('gm_untitled/butterbp/dtc19', 0, 1, 'cp : 6.1255 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/Sub1', 'user2');
annotate_port('gm_untitled/butterbp/Sub1', 0, 1, 'cp : 7.882 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/dtc20', 'user2');
annotate_port('gm_untitled/butterbp/dtc20', 0, 1, 'cp : 7.882 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_untitled/butterbp/dtc21', 'user2');
annotate_port('gm_untitled/butterbp/dtc21', 0, 1, 'cp : 7.882 ns');
